version: '3'
services:
  app:
#    build 会自动找到。目录下的dockfile进行构建
    build: src/main/java
#    image: 使用提前构建好的docker
#    image: my-app-image
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=BDS
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: BDS
      MYSQL_DATABASE: project
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mysql_data:
