spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/project?serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:BDS}
  profiles:
#    配置开发环境
    active: dev
  session:
#    会话超时时间，单位秒，决定session的有效时间
    timeout: 86400
#    缓存在redis中
    store-type: redis

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    database: 0

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
#        设置cookie的域名。表示cookie只在这个域名下有效
        domain: localhost

xfxh:
  # 服务引擎使用 讯飞星火认知大模型V2.0，如果使用 V1.5 需要将 hostUrl 修改为 https://spark-api.xf-yun.com/v1.1/chat
  hostUrl: https://spark-api.xf-yun.com/v3.5/chat
  # 发送请求时指定的访问领域，如果是 V1.5版本 设置为 general，如果是 V2版本 设置为 generalv2
  domain: generalv3.5
  # 核采样阈值。用于决定结果随机性，取值越高随机性越强即相同的问题得到的不同答案的可能性越高。取值 [0,1]
  temperature: 0.5
  # 模型回答的tokens的最大长度，V1.5取值为[1,4096]，V2.0取值为[1,8192]。
  maxTokens: 2048
  # 大模型回复问题的最大响应时长，单位 s
  maxResponseTime: 30
  # 允许同时连接大模型的 websocket 数，如果是普通（免费）用户为 2，超过这个数连接响应会报错，具体参考官网。
  QPS: 2
  # 用于权限验证，从服务接口认证信息中获取
  appId: 2369ecb2
  # 用于权限验证，从服务接口认证信息中获取
  apiKey: 7f067087f2dc092fbc681f348568c1db
  # 用于权限验证，从服务接口认证信息中获取
  apiSecret: NGJhMjg5ZWI4ZTI2YjcyZjM5MThkMDVl


mybatis-plus:
  global-config:
    db-config:
#      逻辑删除字段名。这里指定了在数据库表中用于标识记录是否被逻辑删除的字段名称为flag
      logic-delete-field: flag
#      逻辑删除值。这里指定了当数据库表中的flag字段值为1时，表示该记录被逻辑删除。
      logic-delete-value: 1
#      未逻辑删除值。这里指定了当数据库表中的flag字段值为0时，表示该记录未被逻辑删除。
      logic-not-delete-value: 0
  configuration:
#    是否开启驼峰命名自动转换。这里设置为false，表示不自动将数据库字段的下划线命名转换为Java字段的驼峰命名。
    map-underscore-to-camel-case: false
#    sql语句打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    禁用缓存
    local-cache-scope: statement

  # 设置日志打印
  # logging.level.root: 日志级别
  # logging.pattern.console: 日志输出格式
  # %m为消息
  # %n为换行
  # %p 级别
  # %t 为线程名 %16t 则线程名占16位
  # %clr 是添加颜色
  # 例如 %clr（%m） 则日志消息带有颜色
# logging.file.name: 记录日志到文件
# logging.file.logback.rollingpolicy.max-file-size: 日志文件大小
# logging.file.logback.rollingpolicy.file-name-pattern: 超过最大后，重新创建日志文件名称


logging:
  pattern:
#    指定了日志文件的存储路径
    file: "D:\\project\\friends\\friends-backend\\springbootSlf4j\\server.log"
  logback:
#    日志文件滚动策略
    rollingpolicy:
      max-file-size: "10MB"
      file-name-pattern: "D:\\project\\friends\\friends-backend\\springbootSlf4j\\server.%d{yyyy-MM-dd}.%i.log"
  level:
#    将 web 包的日志级别设置为 debug
    web: debug
#    将根日志级别设置为 error
    root: error

knife4j:
  enable: true
# 开启生产环境屏蔽
#  production: true
  openapi:
    title: "伙伴匹配系统"
    description: "伙伴匹配系统后端接口文档"
    email: 969900860@qq.com
    concat: BDS
    url: https://github.com/bai-xiaosheng
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 用户接口
        api-rule: package
        api-rule-resources:
#         这里指定Controller扫描包路径
          - com.example.friendsbackend.controller



#        //分组名称
#        .groupName("2.X版本")
#        .select()
#        .apis(RequestHandlerSelectors.basePackage("com.github.xiaoymin.knife4j.controller"))
#        .paths(PathSelectors.any())
#        .build();





