spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Shanghai
    username: root
    password: BDS
  profiles:
    active: dev
  session:
    timeout: 86400
    store-type: redis
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER

  redis:
    port: 6379
    host: localhost
    database: 1
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
# 开启生产环境屏蔽
#  production: true
  openapi:
    title: "伙伴匹配系统"
    description: "伙伴匹配系统后端接口文档"
    email: 969900860@qq.com
    concat: BDS
    url: https://github.com/bai-xiaosheng
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 用户接口
        api-rule: package
        api-rule-resources:
#         这里指定Controller扫描包路径
          - com.example.friendsbackend.controller



#        //分组名称
#        .groupName("2.X版本")
#        .select()
#        .apis(RequestHandlerSelectors.basePackage("com.github.xiaoymin.knife4j.controller"))
#        .paths(PathSelectors.any())
#        .build();
