# 线上配置环境
# 这个开源时一定不要将这个文件提交，或者不要填写真实配置
# 别攻击我，谢谢了

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/project?serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:BDS}
  profiles:
    active: prod
  session:
    timeout: 86400
    store-type: redis

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    database: 1

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true


